[connections.sql]
url = "mssql+pyodbc://azureuser:YourStrongP%40ssw0rd@newretailserver123.database.windows.net:1433/RetailDB?driver=ODBC+Driver+18+for+SQL+Server&Encrypt=yes&TrustServerCertificate=yes&Connection+Timeout=30"
