# .streamlit/secrets.toml

[connections.sql]
# IMPORTANT: Use ODBC Driver 17 for SQL Server for Streamlit Cloud compatibility
# Make sure your password is URL encoded if it contains special characters (e.g., @ becomes %40)
url = "mssql+pyodbc://azureuser:YourStrongP@ssw0rd@newretailserver123.database.windows.net:1433/RetailDB?driver=ODBC+Driver+17+for+SQL+Server&Encrypt=yes&TrustServerCertificate=yes&ConnectionTimeout=30"
